<?php
    $staff = $block->getStaff();
    $type = $staff['type'] ?? '';
?>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            let type = <?= $type ?>;
            type = (type != 1) && (type != 2) ? '' : 'lv' + type;
            if(type !='')
            {
                let result = '<span style="padding-left: 5px;">('+type+')</span>';
                $(".product-items .product-item .price").append(result);
            }
        });
    });
</script>